# Generated by Django 4.2.1 on 2023-08-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_registration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pro_name", models.CharField(max_length=255)),
                ("pro_price", models.FloatField()),
                ("pro_img", models.CharField(max_length=255)),
            ],
        ),
    ]
