# Generated by Django 4.2.6 on 2023-10-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pro_name", models.CharField(max_length=255)),
                ("pro_price", models.FloatField()),
                ("pro_img", models.CharField(max_length=255)),
                ("pro_qtn", models.IntegerField()),
                ("pro_total", models.FloatField()),
            ],
        ),
    ]
