# Generated by Django 4.2.6 on 2023-10-13 05:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="pro_qtn",
            new_name="pro_qty",
        ),
        migrations.RenameField(
            model_name="cart",
            old_name="pro_total",
            new_name="pro_tot",
        ),
    ]
