# Generated by Django 4.2.6 on 2023-10-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0005_rename_pro_qtn_cart_pro_qty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="pro_id",
            field=models.IntegerField(null=True),
        ),
    ]
