# Generated by Django 4.2.5 on 2023-10-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0006_cart_pro_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pro_name", models.CharField(max_length=255)),
                ("pro_price", models.FloatField()),
                ("pro_img", models.CharField(max_length=255)),
                ("pro_stock", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="pro_stock",
            field=models.CharField(default=1, max_length=255),
        ),
    ]
