# Generated by Django 4.2.5 on 2023-11-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0007_wishlist_product_pro_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pro_name", models.CharField(max_length=255)),
                ("pro_img", models.CharField(max_length=255)),
            ],
        ),
    ]
