# Generated by Django 4.2.5 on 2023-11-03 05:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0008_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="pro_img",
            new_name="cat_img",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="pro_name",
            new_name="cat_name",
        ),
    ]
