# Generated by Django 4.2.5 on 2023-11-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0010_product_pro_cat"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adminregistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reg_name", models.CharField(max_length=225)),
                ("reg_userid", models.CharField(max_length=255)),
                ("reg_password", models.CharField(max_length=255)),
            ],
        ),
    ]
