# Generated by Django 4.2.5 on 2023-11-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0011_adminregistration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adminuser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admin_name", models.CharField(max_length=225)),
                ("admin_username", models.CharField(max_length=225)),
                ("admin_password", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="Adminregistration",
        ),
    ]
