# Generated by Django 4.2.5 on 2023-11-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0012_adminuser_delete_adminregistration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Productlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pro_img", models.CharField(max_length=255)),
                ("pro_name", models.CharField(max_length=255)),
                ("pro_price", models.FloatField()),
            ],
        ),
    ]
