# Generated by Django 4.2.6 on 2023-12-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0015_delete_adminproduct"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_address", models.CharField(max_length=255)),
                ("order_landmark", models.CharField(max_length=255)),
                ("order_pincode", models.IntegerField()),
                ("order_phone", models.IntegerField()),
                ("order_id", models.IntegerField(null=True)),
                ("order_name", models.CharField(max_length=255)),
                ("order_price", models.FloatField()),
                ("order_img", models.CharField(max_length=255)),
                ("order_qty", models.IntegerField()),
                ("order_tot", models.FloatField()),
            ],
        ),
    ]
