# Generated by Django 4.2.6 on 2023-12-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0016_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_phone",
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_pincode",
            field=models.IntegerField(max_length=6),
        ),
    ]
