# Generated by Django 4.2.6 on 2023-12-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0017_alter_order_order_phone_alter_order_order_pincode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.IntegerField(),
        ),
    ]
