# Generated by Django 4.2.6 on 2023-12-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0020_alter_order_order_qty"),
    ]

    operations = [
        migrations.CreateModel(
            name="Checkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkout_address", models.CharField(max_length=255)),
                ("checkout_landmark", models.CharField(max_length=255)),
                ("checkout_pincode", models.IntegerField(null=True)),
                ("checkout_phone", models.IntegerField(null=True)),
                ("checkout_id", models.IntegerField(null=True)),
                ("checkout_name", models.CharField(max_length=255)),
                ("checkout_price", models.FloatField(null=True)),
                ("checkout_img", models.CharField(max_length=255)),
                ("checkout_qty", models.IntegerField(null=True)),
                ("checkout_tot", models.FloatField()),
            ],
        ),
    ]
