# Generated by Django 4.2.6 on 2023-12-28 04:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0021_checkout"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="order_id",
            new_name="pro_id",
        ),
    ]
