# Generated by Django 4.2.6 on 2024-01-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0022_rename_order_id_order_pro_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_address", models.CharField(max_length=255)),
                ("payment_landmark", models.CharField(max_length=255)),
                ("payment_pincode", models.IntegerField(null=True)),
                ("payment_phone", models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="checkout",
            name="checkout_id",
        ),
        migrations.RemoveField(
            model_name="checkout",
            name="checkout_img",
        ),
        migrations.RemoveField(
            model_name="checkout",
            name="checkout_name",
        ),
        migrations.RemoveField(
            model_name="checkout",
            name="checkout_price",
        ),
        migrations.RemoveField(
            model_name="checkout",
            name="checkout_qty",
        ),
        migrations.RemoveField(
            model_name="checkout",
            name="checkout_tot",
        ),
    ]
