# Generated by Django 4.2.6 on 2024-01-06 04:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0023_payment_remove_checkout_checkout_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
