# Generated by Django 4.2.6 on 2024-02-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0026_cart_pro_user_checkout_pro_user_order_pro_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_status",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
