# Generated by Django 4.2.6 on 2024-02-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0027_order_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
