# Generated by Django 4.2.6 on 2024-02-24 06:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0028_alter_order_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_status",
        ),
    ]
