# Generated by Django 5.0.3 on 2024-03-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0029_remove_order_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_status",
            field=models.IntegerField(default=0),
        ),
    ]
