# Generated by Django 5.0.3 on 2024-03-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0030_order_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="cat_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
